# Generated by Django 2.2.4 on 2019-09-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190829_0530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heading', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
